import {
  AwsDark,
  BetterAuthDark,
  CPlusplus,
  Docker,
  GolangDark,
  Graphql,
  Javascript,
  Kubernetes,
  Mongodb,
  NextjsIconDark,
  Nodejs,
  Postgresql,
  Python,
  ReactDark,
  RustDark,
  ShadcnUiDark,
  Tailwindcss,
  Typescript,
} from "@/components/icons";

export const skills = [
  { label: "Typescript", icon: Typescript, type: "Language" },
  { label: "Rust", icon: RustDark, type: "Language" },
  { label: "Python", icon: Python, type: "Language" },
  { label: "C++", icon: CPlusplus, type: "Language" },
  { label: "Go", icon: GolangDark, type: "Language" },
  { label: "Javascript", icon: Javascript, type: "Language" },
  { label: "React", icon: ReactDark, type: "Framework" },
  { label: "Next.js", icon: NextjsIconDark, type: "Framework" },
  { label: "Node.js", icon: Nodejs, type: "Framework" },
  { label: "Shadcn UI", icon: ShadcnUiDark, type: "UI Library" },
  { label: "Tailwind CSS", icon: Tailwindcss, type: "UI Library" },
  { label: "MongoDB", icon: Mongodb, type: "Database" },
  { label: "Postgres", icon: Postgresql, type: "Database" },
  { label: "GraphQL", icon: Graphql, type: "Database" },
  { label: "AWS", icon: AwsDark, type: "Cloud" },
  { label: "Docker", icon: Docker, type: "Tool" },
  { label: "Kubernetes", icon: Kubernetes, type: "Tool" },
  { label: "Better Auth", icon: BetterAuthDark, type: "Tool" },
];
